### ISSUE TITLE
Password error

### ISSUE THREAD

**Issue by Mcprogramin** [ARBProtocol/jupgrid#21]
(node:6597) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6597) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
Env Loaded Successfully.

Enter your password to decrypt your private key (input hidden): 
Invalid password. Please ensure you are using the correct password.

**Comment by Spuddya7x** [comment]
Please double check the password you added when encoding.

If you cannot remember the password, delete the .env file and run ```node .``` again. This will recreate a blank .env for you to fill in again.
