### ISSUE TITLE
fail transaktion many !

### ISSUE THREAD

**Issue by L2b2n** [ARBProtocol/jupgrid#23]
✖ Attempt 2 - Error in transaction: failed to send transaction: Transaction simulation failed: Error processing Instruction 2: invalid account data for instruction, Full error: {} many many fails

**Comment by Spuddya7x** [comment]
Unfortunately I am going to have to close this. Thank you for reporting it, but without more information, there isnt alot I can do.

Invalid account data shows that there was an error getting your token accounts. Hopefully we can mitigate this happening in the future.
